/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangLeadershipRouteImport } from './routes/$lang/leadership'
import { Route as LangNewsRouteImport } from './routes/$lang/news'
import { Route as LangObjectivesRouteImport } from './routes/$lang/objectives'
import { Route as LangPartnershipsRouteImport } from './routes/$lang/partnerships'
import { Route as LangStrategicActionsRouteImport } from './routes/$lang/strategic-actions'
import { Route as LangVisionMissionRouteImport } from './routes/$lang/vision-mission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLeadershipRoute = LangLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangNewsRoute = LangNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangObjectivesRoute = LangObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPartnershipsRoute = LangPartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangStrategicActionsRoute = LangStrategicActionsRouteImport.update({
  id: '/strategic-actions',
  path: '/strategic-actions',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangVisionMissionRoute = LangVisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/leadership': typeof LangLeadershipRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/objectives': typeof LangObjectivesRoute
  '/$lang/partnerships': typeof LangPartnershipsRoute
  '/$lang/strategic-actions': typeof LangStrategicActionsRoute
  '/$lang/vision-mission': typeof LangVisionMissionRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/leadership': typeof LangLeadershipRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/objectives': typeof LangObjectivesRoute
  '/$lang/partnerships': typeof LangPartnershipsRoute
  '/$lang/strategic-actions': typeof LangStrategicActionsRoute
  '/$lang/vision-mission': typeof LangVisionMissionRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/leadership': typeof LangLeadershipRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/objectives': typeof LangObjectivesRoute
  '/$lang/partnerships': typeof LangPartnershipsRoute
  '/$lang/strategic-actions': typeof LangStrategicActionsRoute
  '/$lang/vision-mission': typeof LangVisionMissionRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/leadership'
    | '/$lang/news'
    | '/$lang/objectives'
    | '/$lang/partnerships'
    | '/$lang/strategic-actions'
    | '/$lang/vision-mission'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/leadership'
    | '/$lang/news'
    | '/$lang/objectives'
    | '/$lang/partnerships'
    | '/$lang/strategic-actions'
    | '/$lang/vision-mission'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/leadership'
    | '/$lang/news'
    | '/$lang/objectives'
    | '/$lang/partnerships'
    | '/$lang/strategic-actions'
    | '/$lang/vision-mission'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/leadership': {
      id: '/$lang/leadership'
      path: '/leadership'
      fullPath: '/$lang/leadership'
      preLoaderRoute: typeof LangLeadershipRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/news': {
      id: '/$lang/news'
      path: '/news'
      fullPath: '/$lang/news'
      preLoaderRoute: typeof LangNewsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/objectives': {
      id: '/$lang/objectives'
      path: '/objectives'
      fullPath: '/$lang/objectives'
      preLoaderRoute: typeof LangObjectivesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/partnerships': {
      id: '/$lang/partnerships'
      path: '/partnerships'
      fullPath: '/$lang/partnerships'
      preLoaderRoute: typeof LangPartnershipsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/strategic-actions': {
      id: '/$lang/strategic-actions'
      path: '/strategic-actions'
      fullPath: '/$lang/strategic-actions'
      preLoaderRoute: typeof LangStrategicActionsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/vision-mission': {
      id: '/$lang/vision-mission'
      path: '/vision-mission'
      fullPath: '/$lang/vision-mission'
      preLoaderRoute: typeof LangVisionMissionRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangLeadershipRoute: typeof LangLeadershipRoute
  LangNewsRoute: typeof LangNewsRoute
  LangObjectivesRoute: typeof LangObjectivesRoute
  LangPartnershipsRoute: typeof LangPartnershipsRoute
  LangStrategicActionsRoute: typeof LangStrategicActionsRoute
  LangVisionMissionRoute: typeof LangVisionMissionRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangLeadershipRoute: LangLeadershipRoute,
  LangNewsRoute: LangNewsRoute,
  LangObjectivesRoute: LangObjectivesRoute,
  LangPartnershipsRoute: LangPartnershipsRoute,
  LangStrategicActionsRoute: LangStrategicActionsRoute,
  LangVisionMissionRoute: LangVisionMissionRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
