/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as StrategicActionsRouteImport } from './routes/strategic-actions'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategicActionsRoute = StrategicActionsRouteImport.update({
  id: '/strategic-actions',
  path: '/strategic-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/objectives': typeof ObjectivesRoute
  '/strategic-actions': typeof StrategicActionsRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/objectives': typeof ObjectivesRoute
  '/strategic-actions': typeof StrategicActionsRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/objectives': typeof ObjectivesRoute
  '/strategic-actions': typeof StrategicActionsRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/objectives' | '/strategic-actions' | '/vision-mission'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/objectives' | '/strategic-actions' | '/vision-mission'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/objectives'
    | '/strategic-actions'
    | '/vision-mission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ObjectivesRoute: typeof ObjectivesRoute
  StrategicActionsRoute: typeof StrategicActionsRoute
  VisionMissionRoute: typeof VisionMissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategic-actions': {
      id: '/strategic-actions'
      path: '/strategic-actions'
      fullPath: '/strategic-actions'
      preLoaderRoute: typeof StrategicActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ObjectivesRoute: ObjectivesRoute,
  StrategicActionsRoute: StrategicActionsRoute,
  VisionMissionRoute: VisionMissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
